name = "[Forge] LOASM"
author = "HRabbit"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ef019594b07a285ab1c432872ac6e18ca0c3bf60ff8daf48f3190ada17b75da"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
